authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('register/', views.register),
    path('register/verify/', views.verifyregistration),
    path('register/verify/resend-code/', views.verifyRegistrationCodeResend),
    path('register/verify/cancel/', views.cancelregistration),

    path('recover/', views.recover),
    path('recover/verify/', views.verifyrecovery),
    path('recover/verify/cancel/', views.cancelrecovery),
    path('recover/verify/resend-code/', views.verifyRecoverCodeResend),
    path('recover/verify/change-password/', views.verifyChangePassword),

    path('account/', views.account, name='account'),
    path('account/close/', views.closeAccount),
    path('account/close/cancel/', views.cancelAccountClosure),
    path('account/close/verify/', views.accountClosure),
    path('account/close/verify/resend-code/', views.resendCloseAccountVerificationCode),
    path('account/change-password/', views.changepassword),
    path('account/get-user/', views.getUser),
    path('account/edit-details/', views.editDetails),
    path('account/edit-email/', views.editEmail),
    path('account/edit-email/verify/', views.edit_email),
    path('account/edit-email/cancel/', views.editEmailCancel),
    path('account/edit-email/verify/resend-code/', views.resentEditEmailVerificationCode)
]

authentication/templates/authentication/account.html
{% extends "authentication/layout.html" %}
{% load static %}


{% block title %}{{request.user.first_name}}{% endblock %}
{% block style %}{% endblock %}


{% block body %}
<div class="container text-center my-5">
    <h5>Account Details</h5><hr>
    <div id="userInfo"></div>
    {% include "authentication/modals/account.html" %}
</div>
{% endblock %}


{% block script %}
<script src="{% static 'authentication/js/account.js' %}"></script>
{% include 'authentication/handlebars/account.html' %}
{% endblock %}

authentication/templates/authentication/header.html
<nav class="navbar navbar-expand-md bg-white text-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Homepage">
            <i class="bi bi-house-door fs-5"></i>
            <span class="badge rounded-pill fs-5 bg-dark text-white">{{sitetitle}}</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#authenticationNavbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="authenticationNavbar">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" onclick="displayChangePasswordModal(event, '{{request.user.id}}')" href="">Change Password</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="" onclick="displayCloseAccountModal(event, '{{request.user.id}}')">Close Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

authentication/templates/authentication/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'authentication/css/layout.css' %}">
        <title>{% block title %}{% endblock %}</title>
        {% block style %}{% endblock %}
    </head>
    <body>
        {% include "authentication/header.html" %}
        {% if messages %}
        <ul class="messages list-unstyled text-center">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }} text-success fs-4"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block body %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.js" integrity="sha512-c7SfJeKRl8g7wgL+zMGX78faYVGp+NZVQ587mRLrqeLySX/qHCQOKw/iZ5Pp64DaPjvedixWC/Fe73upnhBaRA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- Bootstrap Tooltip -->
        <script>
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        </script>
        <!-- Bootstrap Popover -->
        <script>
            const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
            const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
        </script>
        <script src="{% static 'authentication/js/layout.js' %}"></script>
        {% block script %}{% endblock %}
    </body>
</html>

authentication/templates/authentication/login.html
{% extends "authentication/layout.html" %}
{% load static %}


{% block title %}Login{% endblock %}
{% block style %}{% endblock %}


{% block body %}
<div class="container text-center my-5">
    <div class="row">
        <div class="col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        <div class="col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <div class="card mb-3" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">Login</h5>
                    <p class="card-text">
                        <form onsubmit="login(event);">
                            <div class="mb-3">
                                <label for="loginInputEmail" class="form-label"><span class="requirement">*</span>Email / Username</label>
                                <input type="text" class="form-control disableButton" id="loginInputEmail" placeholder="email address or username" autofocus>
                            </div>
                            <div class="mb-3">
                                <label for="loginInputPassword" class="form-label"><span class="requirement">*</span>Password</label>
                                <input type="password" class="form-control disableButton" id="loginInputPassword" placeholder="**********">
                            </div>
                            <button type="submit" class="btn btn-outline-dark disableButton w-100 mt-4">
                                <span class="spinner-border spinner-border-sm text-dark" role="status" aria-hidden="true" hidden></span>
                                Submit
                            </button>
                        </form>
                    </p>
                    <a href="" onclick="displayRegisterModal(event);" class="card-link link-danger-dark disableAnchorTag">Register</a>
                    <a href="" onclick="displayRecoverModal(event);" class="card-link link-danger-dark disableAnchorTag">Recover</a>
                </div>
            </div>
            <div class="errormessage" id="loginError"></div>
        </div>
        <div class="col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
    </div>
    {% include "authentication/modals/register.html" %}
    {% include "authentication/modals/recover.html" %}
</div>
{% endblock %}


{% block script %}
<script src="{% static 'authentication/js/login.js' %}"></script>
<script src="{% static 'authentication/js/register.js' %}"></script>
<script src="{% static 'authentication/js/recover.js' %}"></script>
{% include 'authentication/handlebars/register.html' %}
{% include 'authentication/handlebars/recover.html' %}
{% endblock %}